import Link from "next/link";
import type { Metadata } from "next";
import { SiteFooter } from "@/components/SiteFooter";
import { dataControllerLabel, legalContactEmail } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Privacy & GDPR",
  description: "Fjell Lift privacy notice and GDPR information.",
};

const LAST_UPDATED = "6 April 2026";

export default function PrivacyPage() {
  const controller = dataControllerLabel();
  const contact = legalContactEmail();

  return (
    <div className="flex min-h-full flex-col bg-[var(--background)]">
      <header className="border-b border-teal-900/10 bg-white/90 px-4 py-3 backdrop-blur-sm">
        <Link
          href="/"
          className="text-sm font-medium text-teal-800 hover:text-teal-950 hover:underline"
        >
          ← Home
        </Link>
        <span className="mx-2 text-zinc-300">·</span>
        <Link
          href="/map"
          className="text-sm font-medium text-teal-800 hover:text-teal-950 hover:underline"
        >
          Map
        </Link>
      </header>

      <article className="mx-auto w-full max-w-3xl flex-1 px-4 py-10 text-sm leading-relaxed text-zinc-800">
        <h1 className="text-2xl font-semibold tracking-tight text-zinc-900">
          Privacy notice &amp; GDPR information
        </h1>
        <p className="mt-2 text-xs text-zinc-500">Last updated: {LAST_UPDATED}</p>

        <div className="mt-6 space-y-6">
          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">1. Data controller</h2>
            <p>
              The <strong>data controller</strong> for personal data processed through this
              deployment of Fjell Lift is: <strong>{controller}</strong>.
            </p>
            {contact ? (
              <p>
                Contact for privacy requests:{" "}
                <a className="font-medium text-teal-800 underline" href={`mailto:${contact}`}>
                  {contact}
                </a>
                .
              </p>
            ) : (
              <p className="rounded-xl bg-teal-50/80 p-3 text-xs text-teal-950 ring-1 ring-teal-200/60">
                Operators should set{" "}
                <code className="rounded bg-white/80 px-1 py-0.5 font-mono text-[11px]">
                  NEXT_PUBLIC_LEGAL_CONTACT_EMAIL
                </code>{" "}
                in production so users know how to reach you. Until then, use the same support channel
                as for account issues (if any).
              </p>
            )}
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">2. Scope</h2>
            <p>
              This notice describes how we process personal data when you use the Fjell Lift web
              application (accounts, map, practice areas, session experiences, and related features).
              It is intended to meet transparency requirements under the EU/UK{" "}
              <strong>General Data Protection Regulation (GDPR)</strong> and similar laws.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">3. Categories of personal data</h2>
            <ul className="list-inside list-disc space-y-1 text-zinc-700">
              <li>
                <strong>Account data:</strong> email address, name (if provided), profile image URL
                (if provided), identifiers created by Auth.js / Prisma.
              </li>
              <li>
                <strong>Authentication:</strong> magic-link tokens, session records, verification
                tokens (processed to sign you in securely).
              </li>
              <li>
                <strong>Your spots data:</strong> practice area geometry, labels, sport choices, wind
                preferences, public/private flags, and session experience entries you create.
              </li>
              <li>
                <strong>Technical data:</strong> server and hosting logs (e.g. IP address, timestamps,
                URLs) as generated by your hosting provider; not under our direct control in all
                deployments.
              </li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">4. Purposes &amp; legal bases (GDPR)</h2>
            <p>We process personal data for the following purposes and on these bases:</p>
            <ul className="list-inside list-disc space-y-2 text-zinc-700">
              <li>
                <strong>Providing the Service</strong> (account, map, sync) —{" "}
                <strong>Art. 6(1)(b) GDPR</strong> (performance of a contract / steps prior to
                contract) or <strong>Art. 6(1)(f)</strong> (legitimate interests in operating the app).
              </li>
              <li>
                <strong>Security &amp; abuse prevention</strong> (sessions, rate limits, logs) —{" "}
                <strong>Art. 6(1)(f)</strong> legitimate interests.
              </li>
              <li>
                <strong>Email magic links</strong> — <strong>Art. 6(1)(b)</strong> to deliver sign-in
                you requested.
              </li>
              <li>
                <strong>Optional analytics or marketing</strong> — only if the operator adds them
                later, typically <strong>Art. 6(1)(a)</strong> consent. This open-source deployment
                does not include advertising cookies by default.
              </li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">5. Recipients &amp; processors</h2>
            <p>Depending on configuration, data may be processed by:</p>
            <ul className="list-inside list-disc space-y-1 text-zinc-700">
              <li>
                <strong>Hosting &amp; database</strong> (e.g. Render, Vercel, Fly, AWS, etc.) storing
                the application and PostgreSQL.
              </li>
              <li>
                <strong>Email delivery</strong> (SMTP / transactional email provider) for magic
                links.
              </li>
              <li>
                <strong>Map &amp; weather providers</strong> when your browser loads tiles or when our
                servers call forecast APIs (typically location coordinates without directly attaching
                your name to those calls).
              </li>
            </ul>
            <p>
              We use written agreements with processors where required (Art. 28 GDPR) when we appoint
              them as sub-processors.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">6. Transfers outside the EEA</h2>
            <p>
              If servers or subprocessors are located outside the European Economic Area, we rely on
              appropriate safeguards such as Standard Contractual Clauses or adequacy decisions, as
              required by Chapter V GDPR.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">7. Retention</h2>
            <p>
              We keep account and content data until you delete it or close your account, or until
              the operator removes an inactive deployment. Session tokens expire per Auth.js
              configuration (e.g. 30 days). Server logs follow the hosting provider&apos;s retention.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">8. Your rights (GDPR)</h2>
            <p>Where GDPR applies, you may have the right to:</p>
            <ul className="list-inside list-disc space-y-1 text-zinc-700">
              <li>Access your personal data (Art. 15)</li>
              <li>Rectification (Art. 16)</li>
              <li>Erasure (&quot;right to be forgotten&quot;) (Art. 17)</li>
              <li>Restriction of processing (Art. 18)</li>
              <li>Data portability (Art. 20)</li>
              <li>Object to processing based on legitimate interests (Art. 21)</li>
              <li>Withdraw consent at any time, where processing is consent-based (Art. 7(3))</li>
              <li>
                Lodge a complaint with a supervisory authority (Art. 77), e.g. in your country of
                residence
              </li>
            </ul>
            <p>
              To exercise rights, contact the controller using the email above (when configured) or
              your operator&apos;s published support channel.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">9. Cookies &amp; similar technologies</h2>
            <p>
              The Service uses cookies or secure storage as needed for session management (e.g.
              NextAuth session cookie). These are typically <strong>strictly necessary</strong> for
              authentication. We do not use third-party advertising cookies in the default open-source
              build.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">10. Children</h2>
            <p>
              The Service is not directed at children under 16. Do not provide personal data of
              children without appropriate consent under local law.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-zinc-900">11. Changes</h2>
            <p>
              We may update this notice. We will adjust the &quot;Last updated&quot; date and, where
              required, provide additional notice.
            </p>
          </section>

          <section className="space-y-2 rounded-xl bg-zinc-100/80 p-4 text-xs text-zinc-600 ring-1 ring-zinc-200/80">
            <p>
              <strong>Disclaimer:</strong> This text is a practical template for self-hosted and
              small-team deployments. It is not legal advice. Operators should have terms and privacy
              documents reviewed by qualified counsel for their jurisdiction, data flows, and hosting
              choices.
            </p>
            <p className="mt-2">
              Related:{" "}
              <Link href="/terms" className="font-medium text-teal-800 underline">
                Terms of use (EULA)
              </Link>
              .
            </p>
          </section>
        </div>
      </article>

      <SiteFooter />
    </div>
  );
}
